/** Emojis alignés sur `app/pages/account/badges.vue` (+ paliers Te Natira'a 10 / 20). */
const BADGE_EMOJI_BY_CODE: Record<string, string> = {
  academy_courses_completed_1: '🛡️',
  academy_courses_completed_5: '🌊',
  academy_courses_completed_15: '📜',
  academy_courses_completed_25: '🏛️',
  blog_articles_validated_1: '✍️',
  blog_articles_validated_3: '📝',
  blog_articles_validated_10: '📰',
  blog_articles_validated_25: '📋',
  academy_formateur_points_1: '🌱',
  academy_formateur_points_3: '🪴',
  academy_formateur_points_5: '🌳',
  academy_formateur_points_10: '🏛️',
  troc_exchanges_completed_1: '🤝',
  troc_exchanges_completed_10: '🔄',
  troc_exchanges_completed_50: '⚓',
  troc_exchanges_completed_100: '🏆',
  referral_filleuls_valides_1: '🎖️',
  referral_filleuls_valides_5: '🛶',
  referral_filleuls_valides_15: '🧭',
  referral_filleuls_valides_50: '🏛️',
  soutien_points_1: '🤲',
  soutien_points_5: '💎',
  soutien_points_10: '💝',
  soutien_points_20: '🏛️',
  tenatiraa_presence_1: '🕯️',
  tenatiraa_presence_2: '🪷',
  tenatiraa_presence_3: '🏛️',
  tenatiraa_presence_5: '🦅',
  tenatiraa_presence_10: '🏵️',
  tenatiraa_presence_20: '🌟',
  culture_contents_viewed_1: '👁️',
  culture_contents_viewed_5: '📦',
  culture_contents_viewed_20: '🔍',
  culture_contents_viewed_50: '🗄️',
  testimonial_video_validated_1: '🎤',
  testimonial_video_validated_3: '📢',
  testimonial_video_validated_5: '📖',
  testimonial_video_validated_10: '🏛️',
  discovery_first_step: '🔦',
  discovery_three_universes_one_each: '🗺️',
  discovery_five_action_types: '🌅',
  discovery_two_each_universe: '🏛️',
  special_founder_2026: '🏴',
  special_troc_pioneer_may_2026: '🚀',
  special_pupu_collector_500: '🐚',
  special_vip_heritage: '👑',
  special_badges_total_10: '📛',
  special_badges_total_20: '🎖️',
  special_toa_community: '⚔️',
  special_respect_anciens: '🌺',
}

export function useBadgeEmoji() {
  function badgeEmoji(code: string): string {
    return BADGE_EMOJI_BY_CODE[code] ?? '🏅'
  }
  return { badgeEmoji }
}
